[tools]
biome = "latest"
neovim = "latest"
rclone = "latest"
node = "latest"
pnpm = "latest"
ruff = "latest"
python = "latest"
pre-commit = "latest"
conan = "latest"
npm = "latest"
tmux = "latest"
aws-cli = { version = "latest", symlink_bins = "true" }
opencode = "latest"
aws-sam = { version = "latest", symlink_bins = "true" }
tree-sitter = "latest"
uv = "latest"
go = "latest"
kind = "latest"
golangci-lint = "latest"
rust = "latest"
grpcurl = "latest"
"cargo:raine/workmux" = "latest"
jq = "latest"
k9s = "latest"
gh = "latest"
glab = { version = "latest", exe = "glab" }
cmake = "latest"
claude-code = "latest"
postgres = "latest"
