set -ga terminal-features "xterm-ghostty:RGB:sync"

set -sg escape-time 0
set -g history-limit 100000
set -g renumber-windows on
set -g set-clipboard on

unbind C-b
set -g prefix C-a
bind C-a send-prefix

set -g status-position bottom
set -g status-style "bg=terminal,fg=terminal"

set -g status-left ""
set -g status-right ""
set -g status-justify centre

set -g window-status-current-format "  #W  "
set -g window-status-format "  #W  "
set -g window-status-current-style "bg=colour252,fg=black"
set -g window-status-style "bg=terminal,fg=terminal"

set -g focus-events on

setw -g mouse on

bind | split-window -h -c "#{pane_current_path}"
bind _ split-window -v -c "#{pane_current_path}"

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -n M-1 select-window -t 0
bind -n M-2 select-window -t 1
bind -n M-3 select-window -t 2
bind -n M-4 select-window -t 3
bind -n M-5 select-window -t 4
bind -n M-6 select-window -t 5
bind -n M-7 select-window -t 6
bind -n M-8 select-window -t 7
bind -n M-9 select-window -t 8

# set-hook -g after-new-window "split-window -v -l 20% -d -c '#{pane_current_path}'"

bind -n C-l send-keys C-l \; clear-history

bind r source-file ~/.tmux.conf

set-hook -g session-created "new-window ; new-window ; select-window -t 0"
